# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1180, 592)
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 95 ExtraBold")
        Form.setFont(font)
        Form.setStyleSheet("")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("border-radius:8px;\n"
                                  "background-color: rgb(232, 244, 244);")
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.maximize_btn2 = QtWidgets.QPushButton(self.widget_2)
        self.maximize_btn2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 65 Medium")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.maximize_btn2.setFont(font)
        self.maximize_btn2.setStyleSheet("text-align:left;\n"
                                         "padding:5px;")
        self.maximize_btn2.setText("")
        self.maximize_btn2.setObjectName("maximize_btn2")
        self.horizontalLayout_4.addWidget(self.maximize_btn2)
        self.minimize_btn = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Alibaba PuHuiTi 2.0")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.minimize_btn.setFont(font)
        self.minimize_btn.setToolTip("")
        self.minimize_btn.setStyleSheet("QPushButton{\n"
                                        "  width:40px;\n"
                                        "  height:30px;\n"
                                        "  image:url(image/minimize.png);\n"
                                        "  border-radius:8px\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "  background-color: rgb(222, 222, 222);\n"
                                        "}")
        self.minimize_btn.setText("")
        self.minimize_btn.setIconSize(QtCore.QSize(15, 15))
        self.minimize_btn.setObjectName("minimize_btn")
        self.horizontalLayout_4.addWidget(self.minimize_btn)
        self.maximize_btn = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Alibaba PuHuiTi 2.0")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.maximize_btn.setFont(font)
        self.maximize_btn.setToolTip("")
        self.maximize_btn.setStyleSheet("QPushButton{\n"
                                        "  width:40px;\n"
                                        "  height:30px;\n"
                                        "  image:url(image/maximize.png);\n"
                                        "  border-radius:8px\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "  background-color: rgb(222, 222, 222);\n"
                                        "}")
        self.maximize_btn.setText("")
        self.maximize_btn.setIconSize(QtCore.QSize(15, 15))
        self.maximize_btn.setObjectName("maximize_btn")
        self.horizontalLayout_4.addWidget(self.maximize_btn)
        self.exit_btn = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Alibaba PuHuiTi 2.0")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.exit_btn.setFont(font)
        self.exit_btn.setToolTip("")
        self.exit_btn.setStyleSheet("QPushButton{\n"
                                    "  width:40px;\n"
                                    "  height:30px;\n"
                                    "  image:url(image/close2.png);\n"
                                    "  border-radius:8px\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "  image:url(image/close3.png);\n"
                                    "  background-color: rgb(232, 17, 35)\n"
                                    "}")
        self.exit_btn.setText("")
        self.exit_btn.setIconSize(QtCore.QSize(15, 15))
        self.exit_btn.setObjectName("exit_btn")
        self.horizontalLayout_4.addWidget(self.exit_btn)
        self.horizontalLayout_4.setStretch(0, 1)
        self.verticalLayout.addWidget(self.widget_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, 5, -1)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.setting_btn = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.setting_btn.setFont(font)
        self.setting_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.setting_btn.setStyleSheet("QPushButton{\n"
                                       "  width:40px;\n"
                                       "  height:40px;\n"
                                       "  border:none;\n"
                                       "  image: url(image/settings.png)\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "  image: url(image/settings1.png)\n"
                                       "}")
        self.setting_btn.setText("")
        self.setting_btn.setIconSize(QtCore.QSize(35, 35))
        self.setting_btn.setObjectName("setting_btn")
        self.horizontalLayout_7.addWidget(self.setting_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 65 Medium")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setStyleSheet("width:506;\n"
                                    "height:35;\n"
                                    "padding:5px;\n"
                                    "border-radius:15px;\n"
                                    "background-color: rgb(255, 255, 255);\n"
                                    "")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.extract_btn = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 55 Regular")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.extract_btn.setFont(font)
        self.extract_btn.setStyleSheet("\n"
                                       "QPushButton{\n"
                                       "  height:46px;\n"
                                       "  width:64px;\n"
                                       "  color:rgb(0,0,0);\n"
                                       "  background-color: rgb(0, 170, 127);\n"
                                       "  border-radius:15px\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "  background-color: rgb(0, 238, 175)\n"
                                       "}\n"
                                       "QPushButton:pressed{\n"
                                       "  background-color: rgb(0, 170, 127)\n"
                                       "}")
        self.extract_btn.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.extract_btn.setObjectName("extract_btn")
        self.horizontalLayout_5.addWidget(self.extract_btn)
        self.page_comboBox = QtWidgets.QComboBox(self.widget)
        self.page_comboBox.setMinimumSize(QtCore.QSize(170, 46))
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 95 ExtraBold")
        font.setPointSize(14)
        self.page_comboBox.setFont(font)
        self.page_comboBox.setStyleSheet("border-radius:12px;\n"
                                         "background-color: rgb(255, 255, 255);")
        self.page_comboBox.setObjectName("page_comboBox")
        self.page_comboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.page_comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 5, -1)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.previ_page = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.previ_page.setFont(font)
        self.previ_page.setStyleSheet("QPushButton{\n"
                                      "  width:40px;\n"
                                      "  height:40px;\n"
                                      "  image: url(image/pre_page.png);\n"
                                      "  border:none}\n"
                                      "QPushButton:hover{\n"
                                      "  image: url(image/pre_page1.png)\n"
                                      "}")
        self.previ_page.setText("")
        self.previ_page.setObjectName("previ_page")
        self.horizontalLayout.addWidget(self.previ_page)
        self.page_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体 2.0 65 Medium")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.page_label.setFont(font)
        self.page_label.setStyleSheet("")
        self.page_label.setAlignment(QtCore.Qt.AlignCenter)
        self.page_label.setObjectName("page_label")
        self.horizontalLayout.addWidget(self.page_label)
        self.next_page = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.next_page.setFont(font)
        self.next_page.setStyleSheet("QPushButton{\n"
                                     "  width:40px;\n"
                                     "  height:40px;\n"
                                     "  image: url(image/next_page.png);\n"
                                     "  border:none}\n"
                                     "QPushButton:hover{\n"
                                     "  image: url(image/next_page1.png)\n"
                                     "}\n"
                                     "\n"
                                     "")
        self.next_page.setText("")
        self.next_page.setObjectName("next_page")
        self.horizontalLayout.addWidget(self.next_page)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                      "border-radius:8px;\n"
                                      "border:none")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1178, 412))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_8.addLayout(self.gridLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addWidget(self.widget)

        self.retranslateUi(Form)
        self.lineEdit.returnPressed.connect(Form.drawing_number)
        self.extract_btn.clicked.connect(Form.drawing_number)
        self.next_page.clicked.connect(Form.next)
        self.setting_btn.clicked.connect(Form.settings)
        self.previ_page.clicked.connect(Form.last)
        self.page_comboBox.currentIndexChanged['int'].connect(Form.combobox_histo)
        self.exit_btn.clicked.connect(Form.close)
        self.maximize_btn.clicked.connect(Form.maximize)
        self.minimize_btn.clicked.connect(Form.minimize)
        self.maximize_btn2.clicked.connect(Form.double_click)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "MainWindow"))
        self.maximize_btn2.setToolTip(_translate("Form", "下一页"))
        self.setting_btn.setToolTip(_translate("Form", "设置"))
        self.lineEdit.setToolTip(_translate("Form", "不输入数字按回车默认抽取一个"))
        self.lineEdit.setPlaceholderText(_translate("Form", "请输入要抽取的个数"))
        self.extract_btn.setToolTip(_translate("Form", "不输入数字直接点击抽取默认抽取一个"))
        self.extract_btn.setText(_translate("Form", "抽取"))
        self.page_comboBox.setToolTip(_translate("Form", "历史记录"))
        self.page_comboBox.setItemText(0, _translate("Form", "当前页数:0"))
        self.previ_page.setToolTip(_translate("Form", "上一页"))
        self.page_label.setText(_translate("Form", "1"))
        self.next_page.setToolTip(_translate("Form", "下一页"))
